export enum FieldType {
    NotSupport = 'none',
    Text = 'text',
    Number = 'number',
    SingleSelect = 'single_select',
    MultiSelect = 'multi_select',
    DateTime = 'date_time',
    Attachment = 'attachment',
    Link = 'link',
    URL = 'url',
    Email = 'email',
    Phone = 'phone',
    Checkbox = 'checkbox',
    Rating = 'rating',
    Member = 13,
    LookUp = 14,
    // RollUp = 15,
    Formula = 16,
    Currency = 17,
    Percent = 18,
    SingleText = 19,
    AutoNumber = 20,
    CreatedTime = 21,
    LastModifiedTime = 22,
    CreatedBy = 23,
    LastModifiedBy = 24,
    DeniedField = 999, // no permission column
  }