
export const GRID_OFFSET = {x: 200, y: 20}

export const DEFAULT_CELL_WIDTH = 160
export const DEFAULT_CELL_HEIGHT = 30
export const DEFAULT_ROW_COUNT = 10
export const DEFAULT_COL_COUNT = 4

export const DEFAULT_ROW_WIDTH = DEFAULT_CELL_WIDTH * DEFAULT_COL_COUNT

export const GRID_CONFIG: any = {rows: DEFAULT_ROW_COUNT, cols: DEFAULT_COL_COUNT, cellWidth: DEFAULT_CELL_WIDTH, cellHeight:DEFAULT_CELL_HEIGHT}

export const DEFAULT_ACTIVE_BORDER_COLOR = '#7B67EE'
export const DEFAULT_HOVER_COLOR = 'rgba(0, 2, 180, 0.05)'
export const DEFAULT_CHECKBOX_BORDER_COLOR = '#8c8c8c'